# -*- coding: utf-8 -*-
"""clg1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Khg2ZygkEBxXJDjcI3TDpUxr9Cwxyiiq
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

dataset = pd.read_csv('/content/car_data.csv')
dataset.head()

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values

xtr, xte, ytr, yte = train_test_split(x, y, test_size=0.2, random_state=0)
model = LinearRegression()
model.fit(xtr, ytr)

ypr = model.predict(xte)

plt.scatter(xtr, ytr, color='red')
plt.plot(xtr, model.predict(xtr), color='blue')
plt.title("Mileage Vs selling price:")
plt.xlabel("Mileage")
plt.ylabel("Selling price")
plt.show()

plt.scatter(xte, yte, color='red')
plt.plot(xtr, model.predict(xtr), color='blue')
plt.title("Mileage Vs selling price:")
plt.xlabel("Mileage")
plt.ylabel("Selling price")
plt.show()